INSERT INTO Role (id,roleType,permission)
VALUES (1,'ROLE_USER','READ:USER,READ:CUSTOMER'),
       (2,'ROLE_MANAGER','READ:USER,READ:CUSTOMER,UPDATE:USER,UPDATE:CUSTOMER'),
       (3,'ROLE_ADMIN','READ:USER,READ:CUSTOMER,UPDATE:USER,UPDATE:CUSTOMER,CREATE:USER,CREATE:CUSTOMER'),
       (4,'ROLE_SYSADMIN','READ:USER,READ:CUSTOMER,UPDATE:USER,UPDATE:CUSTOMER,CREATE:USER,CREATE:CUSTOMER,DELETE:USER,DELETE:CUSTOMER');


INSERT INTO event(id, eventType, description)
VALUES(1,'LOGIN_ATTEMPT','descript'),
      (2,'LOGIN_ATTEMPT_FAILURE','descript'),
      (3,'LOGIN_ATTEMPT_SUCCESS','descript'),
      (4,'PROFILE_UPDATE','descript'),
      (5,'PROFILE_PICTURE_UPDATE','descript'),
      (6,'ROLE_UPDATE','descript'),
      (7,'ACCOUNT_SETTINGS_UPDATE','descript'),
      (8,'PASSWORD_UPDATE','descript'),
      (9,'MFA_UPDATE','descript');
